import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:ma_1/utils/app_config.dart';

/// Clinical Gemma Simulation Service
/// Simulates dialogue with specific hospital contacts (technicians, doctors, management)
/// using specialized system instructions and the Gemma-2 model.
class GemmaSimulationService {
  static final GemmaSimulationService instance = GemmaSimulationService._init();
  GemmaSimulationService._init();

  /// Gets the customized system instruction for a specific contact role
  String _getSystemPrompt({
    required String contactId,
    required String contactName,
    required String role,
  }) {
    final basePrompt = '''
You are simulating a live real-time professional chat and call conversation as "$contactName", who is a "$role" at a Zimbabwean clinical hospital.
Your phone number is a public Zimbabwean mobile number (+263 prefix).

YOUR PROFILE AND RESPONSIBILITIES:
''';

    String specificDetails = '';
    switch (contactId) {
      case 'dr-chipo-moyo':
        specificDetails = '''
- Role: ICU Consultant Physician.
- Focus: Patient safety, critical care monitoring, urgent ventilator alarms (Aeonmed VG70, Evita V500), clinical parameters, oxygen cell failures.
- Style: Highly professional, slightly authoritative yet supportive, deeply concerned about patient oxygenation and technical reliability.
- Key technical terms you care about: PEEP, FiO2, tidal volume, compliance, low O2 supply pressure, battery backup status.
''';
        break;
      case 'farai-gumbo':
        specificDetails = '''
- Role: Lead Ventilator Specialist (Biomedical Technician).
- Focus: Calibrations, preventive maintenance, replacement parts (turbines, flow sensors, PEEP valves), pneumatic leak checks.
- Style: Practical, highly technical, peer-to-peer with other BMETs. Uses words like "calibration run", "leak test", "schematics", "rebuild kit".
- Technical focus: Aeonmed VG70 error logs, Dräger Evita V500 pre-use test checklists.
''';
        break;
      case 'tendai-chidi':
        specificDetails = '''
- Role: Medical Gas System Plant Technician.
- Focus: Oxygen plant compressor, pipeline pressure, manifold reserve cylinders, vacuum pumps, flow meters.
- Style: Urgent, mechanical, hands-on, always alerts others about line pressure drops. Speaks about manifold banks, regulator valves, PSI/Bar readings.
- Technical focus: Manifold pressure levels, reserve cylinders pressure, compressor temperature warnings.
''';
        break;
      case 'dr-sekai-nzenza':
        specificDetails = '''
- Role: Chief Medical Officer (CMO).
- Focus: Clinical compliance, patient safety audits, team coordination, ICU capacity planning, incident reporting.
- Style: Encouraging, leadership-oriented, administrative but clinically sharp. Focuses on overall technical status, response times, and patient outcomes.
''';
        break;
      case 'rufaro-moyo':
        specificDetails = '''
- Role: Biomedical Engineering Department Head.
- Focus: Equipment compliance (IEC 60601), spares procurement, maintenance logs auditing, third-party contractor scheduling.
- Style: Administrative, technical, highly organized. Asks about service histories, reorder thresholds, inventory status.
''';
        break;
      case 'kudakwashe-hove':
        specificDetails = '''
- Role: Senior Laboratory Technical Specialist.
- Focus: Blood gas analyzers, lab calibrators, reagents chemistry, automated pipettes.
- Style: Exacting, precise, concerned with micro-calibration, temperature ranges, and reagent expiry dates.
''';
        break;
      default:
        specificDetails = '''
- Role: General Biomedical Engineering Technician.
- Focus: General repairs, asset tracking, support.
- Style: Collaborative, professional, and practical.
''';
    }

    final rulesPrompt = '''
CONVERSATION RULES:
1. Act completely as "$contactName" ($role) at all times.
2. DO NOT state that you are an AI, a language model, or generated by Google.
3. Ground your technical details in genuine clinical engineering practices (e.g. electrical safety checks, gas calibration, manual references).
4. Zimbabwean clinical context: Mention local departments or subtle Zimbabwean English terms (e.g. "Colleague", "Sharp", "Cheers", "Understood, boss" or "We need to fix this asap, my friend") to feel genuine and localized.
5. Message Length:
   - For CHAT: Keep replies short and punchy (1 to 3 sentences) unless a full step-by-step repair instruction is requested.
   - For VOICE CALLS: Keep replies concise (1 to 2 conversational sentences) since they will be read aloud.
''';

    return '$basePrompt$specificDetails\n$rulesPrompt';
  }

  /// Generates a realistic chat response using Gemma-2 (with Gemini fallback)
  Future<String> generateReply({
    required String contactId,
    required String contactName,
    required String role,
    required String userMessage,
    List<Map<String, dynamic>> priorMessages = const [],
    bool isVoiceCall = false,
  }) async {
    if (AppConfig.geminiApiKey.isEmpty ||
        AppConfig.geminiApiKey == 'YOUR_GEMINI_API_KEY_HERE') {
      return _generateOfflineFallback(contactId, userMessage);
    }

    final systemInstruction = _getSystemPrompt(
      contactId: contactId,
      contactName: contactName,
      role: role,
    );

    // Build complete conversational context
    final List<Content> contents = [];
    
    // Process recent messages (limit to last 6 for prompt size and efficiency)
    final recentHistory = priorMessages.length > 6
        ? priorMessages.sublist(priorMessages.length - 6)
        : priorMessages;

    for (final msg in recentHistory) {
      final text = msg['message_text']?.toString() ?? '';
      if (text.isEmpty) continue;

      final senderId = msg['sender_id']?.toString();
      final isCurrentUser = senderId == 'local-technician' || senderId == 'CURRENT-TECH' || senderId == 'local';

      if (isCurrentUser) {
        contents.add(Content.text(text));
      } else {
        contents.add(Content.model([TextPart(text)]));
      }
    }

    // Add current user prompt
    final currentPrompt = isVoiceCall
        ? 'LIVE CALL AUDIO: "$userMessage"'
        : userMessage;
    contents.add(Content.text(currentPrompt));

    // Try Gemma model first as requested, fallback to Gemini if model is unavailable
    try {
      final model = GenerativeModel(
        model: AppConfig.simulationModel,
        apiKey: AppConfig.geminiApiKey,
        systemInstruction: Content.system(systemInstruction),
        generationConfig: GenerationConfig(
          temperature: 0.7,
          maxOutputTokens: isVoiceCall ? 128 : 256,
          topP: 0.95,
        ),
      );

      final response = await model.generateContent(contents);
      final text = response.text;
      if (text != null && text.trim().isNotEmpty) {
        return text.trim();
      }
    } catch (e) {
      // Clean fallback to gemini-2.5-flash
      try {
        final fallbackModel = GenerativeModel(
          model: 'gemini-2.5-flash',
          apiKey: AppConfig.geminiApiKey,
          systemInstruction: Content.system(systemInstruction),
          generationConfig: GenerationConfig(
            temperature: 0.7,
            maxOutputTokens: isVoiceCall ? 128 : 256,
            topP: 0.95,
          ),
        );
        final response = await fallbackModel.generateContent(contents);
        final text = response.text;
        if (text != null && text.trim().isNotEmpty) {
          return text.trim();
        }
      } catch (fallbackError) {
        return 'Network latency error. Let me try sending that again shortly.';
      }
    }

    return _generateOfflineFallback(contactId, userMessage);
  }

  /// Offline rule-based fallback responses for reliable operation without API access
  String _generateOfflineFallback(String contactId, String query) {
    final lower = query.toLowerCase();
    switch (contactId) {
      case 'dr-chipo-moyo':
        if (lower.contains('alarm') || lower.contains('fault')) {
          return 'Understood. Is the patient safe? Please switch them to manual ventilation if the VG70 continues to drop pressure, colleague. I am headed to the unit now.';
        }
        return 'Colleague, let\'s prioritize the ICU ventilator audit. Let me know when SN-VG70-442 is checked.';
      case 'farai-gumbo':
        if (lower.contains('calibration') || lower.contains('test')) {
          return 'For calibration, check the flow sensor alignment on the Evita V500. A tiny volume leak is normal but let\'s keep it under 50mL/min. Let me know what you find.';
        }
        return 'I have the turbine repair kits ready on Shelf B2. Let me know if you need assistance mounting it, colleague.';
      case 'tendai-chidi':
        return 'The pipeline pressure is dropping below 4.2 bar at the gas manifold! Please confirm that ICU has switched over to reserve cylinders before we check the compressor.';
      default:
        return 'Acknowledged, colleague. Let\'s coordinate and make sure technical compliance is documented in our service reports.';
    }
  }
}
